#!/bin/bash

echo "📱 Manual App Installation Guide"
echo "================================"
echo ""

echo "STEP 1: Verify Device Connection"
echo "--------------------------------"
echo "Run this command to check if your iPhone is connected:"
echo "xcrun devicectl list devices"
echo ""

echo "STEP 2: Build for Device (Not Simulator)"
echo "---------------------------------------"
echo "In Xcode:"
echo "1. Select your iPhone from the device dropdown (top left)"
echo "2. Make sure it says your iPhone name, not 'Any iOS Device'"
echo "3. Press ⌘R (Product > Run)"
echo ""

echo "STEP 3: Watch for Installation Progress"
echo "--------------------------------------"
echo "You should see:"
echo "1. 'Building...' in the status bar"
echo "2. 'Installing...' in the status bar"
echo "3. 'Running...' when complete"
echo ""

echo "STEP 4: Check Installation Logs"
echo "-------------------------------"
echo "If installation fails:"
echo "1. In Xcode: View > Debug Area > Show Debug Area"
echo "2. Look for red error messages"
echo "3. Common issues:"
echo "   - 'Code signing error' → Check signing settings"
echo "   - 'Device not found' → Reconnect iPhone"
echo "   - 'Unable to install' → Trust computer on iPhone"
echo ""

echo "STEP 5: Alternative - Use Devices Window"
echo "---------------------------------------"
echo "1. In Xcode: Window > Devices and Simulators"
echo "2. Select your iPhone"
echo "3. Click the '+' button under 'Installed Apps'"
echo "4. Navigate to your .app file and install"
echo ""

echo "STEP 6: Verify Installation"
echo "---------------------------"
echo "After successful installation:"
echo "1. Check iPhone Settings > General > VPN & Device Management"
echo "2. You should now see your developer profile"
echo "3. Trust the profile"
echo "4. App should appear on home screen"
echo ""

echo "🚨 TROUBLESHOOTING:"
echo "==================="
echo "If still not working:"
echo "1. Restart Xcode"
echo "2. Disconnect and reconnect iPhone"
echo "3. Clean Build Folder (⌘⇧K)"
echo "4. Delete app from iPhone if partially installed"
echo "5. Try again with ⌘R"