name: AreaBook
options:
  bundleIdPrefix: com.areabook
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  AreaBook:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - AreaBook
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.areabook.ios
      DEVELOPMENT_ASSET_PATHS: '"AreaBook/Preview Content"'
      ENABLE_PREVIEWS: true
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    dependencies:
      - package: Firebase
        products:
          - FirebaseAuth
          - FirebaseFirestore
          - FirebaseStorage
          - FirebaseMessaging
          - FirebaseAnalytics
          - FirebaseCrashlytics
    info:
      path: AreaBook/Info.plist
      properties:
        CFBundleDisplayName: AreaBook
        CFBundleName: AreaBook
        CFBundleIdentifier: com.areabook.ios
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        NSUserNotificationsUsageDescription: "This app uses notifications to remind you about tasks and goals."
        NSCameraUsageDescription: "This app uses the camera to add photos to your notes and goals."
        NSPhotoLibraryUsageDescription: "This app uses the photo library to add images to your notes and goals."

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "10.0.0"
    products:
      - FirebaseAuth
      - FirebaseFirestore
      - FirebaseStorage
      - FirebaseMessaging
      - FirebaseAnalytics
      - FirebaseCrashlytics

schemes:
  AreaBook:
    build:
      targets:
        AreaBook: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release 